package mx.com.afasa.entities;
// Generated 31-mar-2019 21:37:53 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CtEventos generated by hbm2java
 */
public class CT_EVENTOS  implements java.io.Serializable {


     private Integer PK_EVENTO;
     private String NOMBRE;
     private String NUMERO;
     private Integer MARCA;
     private String IMAGEN_NOMBRE;
     private String IMAGEN_CONTENT;
     private Set trEventosEjecucions = new HashSet(0);
     
     private String strMarca;

    public CT_EVENTOS() {
    }

    public CT_EVENTOS(Integer PK_EVENTO) {
        this.PK_EVENTO = PK_EVENTO;
    }
     
     

    public Integer getPK_EVENTO() {
        return PK_EVENTO;
    }

    public void setPK_EVENTO(Integer PK_EVENTO) {
        this.PK_EVENTO = PK_EVENTO;
    }

    public String getNOMBRE() {
        return NOMBRE;
    }

    public void setNOMBRE(String NOMBRE) {
        this.NOMBRE = NOMBRE;
    }

    public String getNUMERO() {
        return NUMERO;
    }

    public void setNUMERO(String NUMERO) {
        this.NUMERO = NUMERO;
    }

    public Integer getMARCA() {
        return MARCA;
    }

    public void setMARCA(Integer MARCA) {
        this.MARCA = MARCA;
    }

    public String getIMAGEN_NOMBRE() {
        return IMAGEN_NOMBRE;
    }

    public void setIMAGEN_NOMBRE(String IMAGEN_NOMBRE) {
        this.IMAGEN_NOMBRE = IMAGEN_NOMBRE;
    }

    public String getIMAGEN_CONTENT() {
        return IMAGEN_CONTENT;
    }

    public void setIMAGEN_CONTENT(String IMAGEN_CONTENT) {
        this.IMAGEN_CONTENT = IMAGEN_CONTENT;
    }

    public Set getTrEventosEjecucions() {
        return trEventosEjecucions;
    }

    public void setTrEventosEjecucions(Set trEventosEjecucions) {
        this.trEventosEjecucions = trEventosEjecucions;
    }

    public String getStrMarca() {
        return strMarca;
    }

    public void setStrMarca(String strMarca) {
        this.strMarca = strMarca;
    }

  
    


}


